In [ ]:
class Bag:
    def __init__(self):
        self.data = []

    def add(self, x):
        self.data.append(x)



In [ ]:
a = Bag


In [ ]:
a().add(a)

In [ ]:
p = 5

In [ ]:
p -= 1
p

In [ ]:
p // 2

In [ ]:
b = list()
b.insert(50,5)

In [ ]:
10.5%1

In [ ]:
1 % 2

In [ ]:
round(1.25)

In [ ]:
(2**4-6)*2**7

In [ ]:
((2*2-1)*2-1)*2**8

In [ ]:
(2**4-7)*2**7

In [ ]:
import math
a = 1152
w = math.floor(math.log(896,2))
w

In [ ]:
a - 2**w

In [ ]:
math.log(896,2)

In [ ]:
896 - 2**9


In [ ]:
math.log(384,2)

In [ ]:
384 - 2**8

In [ ]:
math.log(128,2)

In [ ]:
2*2**10-896

In [ ]:
(2*2-1)*2**9-384

In [ ]:
((2*2-1)*2-1)*2**8-128

In [ ]:
(((2*2-1)*2-1)*2-1)*2**7

In [ ]:
2*2**10-896

In [ ]:
100*2**7

In [ ]:
2801-753

In [ ]:
2**11

In [ ]:
data = (1,4, None)
a = (data)

In [1]:
a = [2,3,4]

In [2]:
a

[2, 3, 4]

In [3]:
import heapq

In [4]:
h = []
for value in a:
    heapq.heappush(h, value)

In [111]:
try:
    a = heapq.heappop(h)
except IndexError:
    print('haha')

haha


In [38]:
v = (2,6)
g = [0,0]
g[1]=v

In [43]:
g = [0,0]

In [44]:
v2 = (3,5)
g[1]=g[1],v2
g[1]=tuple(g[1])

In [45]:
g[1]=tuple(g[1])

In [46]:
g

[0, (0, (3, 5))]

In [102]:
vdict = dict(shortest = 999999, final = False, prev = None)
vdata = [dict(shortest = 999999, final = False, prev = None) for _ in range(5)]

In [103]:
vdata[1]['shortest'] = 5

In [104]:
vdata

[{'shortest': 999999, 'final': False, 'prev': None},
 {'shortest': 5, 'final': False, 'prev': None},
 {'shortest': 999999, 'final': False, 'prev': None},
 {'shortest': 999999, 'final': False, 'prev': None},
 {'shortest': 999999, 'final': False, 'prev': None}]

In [86]:
ee = {'a':4,'b':5}

In [87]:
dd

{'a': 5, 'b': 6}

In [88]:
ee

{'a': 4, 'b': 5}

In [112]:
import numpy as np

In [114]:
n = 3
g_array = np.zeros([n,n])
g_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [146]:
g_array[1, 1] = 2

In [147]:
g_array

array([[3., 0., 0.],
       [0., 2., 3.],
       [0., 0., 0.]])

In [141]:
np.where(np.any(g_array[1]>0,axis=0))

(array([0], dtype=int64),)

In [191]:
edges = np.transpose((g_array[1] > 0).nonzero())
edges

array([[1],
       [2]], dtype=int64)

In [192]:
for neigbo in edges:
    print(neigbo[0])

1
2


In [193]:
final = [False for _ in range(3)]

In [194]:
final

[False, False, False]

In [201]:
final[2] = True

In [196]:
final

[True, False, False]

In [202]:
if all(final):
    print('yes')

yes


In [207]:
g_list = [[]] * 5

In [208]:
g_list

[[], [], [], [], []]

In [250]:
a = (i for i in range(1, 5))

In [261]:
b = dict.fromkeys(range(1, 5), [])

In [275]:
c = dict.fromkeys((i for i in range(1, 5)), True)
c[1] = True

In [276]:
all(c.values())

True

In [269]:
if c.values():
    print('yes')

yes


In [279]:
import math
shortest = {(math.inf,i) for i in range(2,n+1)}

In [280]:
shortest

{(inf, 2), (inf, 3)}

In [294]:
a = [0,1,2]

In [295]:
a.remove(len(a)-1)

In [296]:
a

[0, 1]

In [ ]:
while a